server:
  port: 8080

spring:
  application:
    name: ferie-service
  datasource:
    url: jdbc:h2:mem:feriedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: ADMIN
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none

flowable:
  async-executor-activate: false

logging:
  level:
    org.flowable: INFO
    com.example: DEBUG